# Auto-generated by scripts/stage5_internimage_runner.py
_base_ = r"D:/detr_Q3/external_code/InternImage/detection/configs/coco/mask_rcnn_internimage_t_fpn_3x_coco.py"
custom_imports = dict(imports=['mmdet_custom'], allow_failed_imports=False)

classes = ('smoke', 'fire')
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=4,
    persistent_workers=True,
    pin_memory=True,
    train=dict(
        ann_file=r"D:/detr_Q3/data/stage5_internimage/dfire/annotations/train_baseline.json",
        img_prefix='',
        classes=classes),
    val=dict(
        ann_file=r"D:/detr_Q3/data/stage5_internimage/dfire/annotations/eval_all.json",
        img_prefix='',
        classes=classes),
    test=dict(
        ann_file=r"D:/detr_Q3/data/stage5_internimage/dfire/annotations/eval_all.json",
        img_prefix='',
        classes=classes))

model = dict(
    backbone=dict(core_op='DCNv3_pytorch', with_cp=False),
    roi_head=dict(
        bbox_head=dict(num_classes=2),
        mask_head=dict(num_classes=2)))

runner = dict(type='EpochBasedRunner', max_epochs=300)
evaluation = dict(interval=300, metric=['bbox'], save_best='bbox_mAP')
checkpoint_config = dict(interval=1, max_keep_ckpts=3, save_last=True)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])

seed = 22
gpu_ids = [0]


