import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ARM_ORDER = ("baseline", "baseline_eqstep", "hardneg", "hardneg_sched")
ARM_GROUPS = {
    "baseline": ["baseline"],
    "baseline_eqstep": ["baseline_eqstep"],
    "hardneg": ["hardneg"],
    "hardneg_sched": ["hardneg_sched"],
    "all4": list(ARM_ORDER),
}


def rel(path):
    return str((ROOT / path).resolve()).replace("\\", "/")


def native(path):
    return str((ROOT / path).resolve())


def run(cmd, cwd=None):
    print("[cmd] " + " ".join(map(str, cmd)))
    subprocess.run(list(map(str, cmd)), cwd=cwd, check=True)


def ensure_inputs():
    needed = [
        "external_code/InternImage/detection/train.py",
        "external_code/InternImage/detection/test.py",
        "external_code/InternImage/detection/configs/coco/mask_rcnn_internimage_t_fpn_3x_coco.py",
        "data/stage5_internimage/dfire/annotations/eval_all.json",
    ]
    missing = [p for p in needed if not (ROOT / p).exists()]
    if missing:
        raise SystemExit("[error] missing inputs; run stage5_internimage\\00_prepare_dfire_coco.bat first:\n" + "\n".join(missing))


def patch_mmdet_collect_env():
    return


def arm_ann(arm):
    return rel(f"data/stage5_internimage/dfire/annotations/train_{arm}.json")


def config_text(args, arm, epochs):
    base = rel("external_code/InternImage/detection/configs/coco/mask_rcnn_internimage_t_fpn_3x_coco.py")
    train_ann = arm_ann(arm)
    eval_ann = rel("data/stage5_internimage/dfire/annotations/eval_all.json")
    return f'''# Auto-generated by scripts/stage5_internimage_runner.py
_base_ = r"{base}"
custom_imports = dict(imports=['mmdet_custom'], allow_failed_imports=False)

classes = ('smoke', 'fire')
data = dict(
    samples_per_gpu={args.batch},
    workers_per_gpu={args.workers},
    persistent_workers=True,
    pin_memory=True,
    train=dict(
        ann_file=r"{train_ann}",
        img_prefix='',
        classes=classes),
    val=dict(
        ann_file=r"{eval_ann}",
        img_prefix='',
        classes=classes),
    test=dict(
        ann_file=r"{eval_ann}",
        img_prefix='',
        classes=classes))

model = dict(
    backbone=dict(core_op='DCNv3_pytorch', with_cp=False),
    roi_head=dict(
        bbox_head=dict(num_classes=2),
        mask_head=dict(num_classes=2)))

runner = dict(type='EpochBasedRunner', max_epochs={epochs})
evaluation = dict(interval={max(1, epochs)}, metric=['bbox'], save_best='bbox_mAP')
checkpoint_config = dict(interval=1, max_keep_ckpts=3, save_last=True)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])

seed = {args.seed}
gpu_ids = [{args.device}]
'''


def config_path(args, arm, epochs):
    cfg_dir = ROOT / "stage5_internimage" / "configs" / "dfire"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    suffix = "min" if epochs < args.epochs else "formal"
    path = cfg_dir / f"internimage_t_maskrcnn_seed{args.seed}_{arm}_{suffix}.py"
    path.write_text(config_text(args, arm, epochs), encoding="utf-8")
    return path


def run_dir(args, arm):
    return ROOT / args.run_root / f"dfire_internimage_t_maskrcnn_seed{args.seed}" / arm


def out_dir(args):
    return ROOT / args.out_root / f"dfire_internimage_t_maskrcnn_seed{args.seed}"


def train_arm(args, arm, epochs):
    work = run_dir(args, arm)
    if work.exists() and args.overwrite:
        shutil.rmtree(work)
    if work.exists() and not args.overwrite:
        raise SystemExit(f"[error] train dir exists: {work}")
    work.mkdir(parents=True, exist_ok=True)
    cfg = config_path(args, arm, epochs)
    env = os.environ.copy()
    det_root = ROOT / "external_code" / "InternImage" / "detection"
    env["PYTHONPATH"] = str(det_root) + os.pathsep + env.get("PYTHONPATH", "")
    cmd = [
        sys.executable,
        str(det_root / "train.py"),
        str(cfg),
        "--work-dir",
        str(work),
        "--seed",
        str(args.seed),
        "--gpu-id",
        str(args.device),
    ]
    print("[cmd] " + " ".join(cmd))
    subprocess.run(cmd, cwd=det_root, env=env, check=True)


def find_checkpoint(work):
    best = sorted(work.glob("best_*.pth"), key=lambda p: p.stat().st_mtime, reverse=True)
    if best:
        return best[0]
    last = work / "latest.pth"
    if last.exists():
        return last
    candidates = sorted(work.glob("epoch_*.pth"), key=lambda p: p.stat().st_mtime, reverse=True)
    if candidates:
        return candidates[0]
    raise SystemExit(f"[error] no checkpoint found under {work}")


def export_arm(args, arm, epochs):
    work = run_dir(args, arm)
    checkpoint = find_checkpoint(work)
    cfg = config_path(args, arm, epochs)
    out = out_dir(args)
    out.mkdir(parents=True, exist_ok=True)
    pkl = out / f"{arm}.pkl"
    det_root = ROOT / "external_code" / "InternImage" / "detection"
    env = os.environ.copy()
    env["PYTHONPATH"] = str(det_root) + os.pathsep + env.get("PYTHONPATH", "")
    cmd = [
        sys.executable,
        str(det_root / "test.py"),
        str(cfg),
        str(checkpoint),
        "--out",
        str(pkl),
        "--eval",
        "bbox",
        "--gpu-ids",
        str(args.device),
    ]
    print("[cmd] " + " ".join(cmd))
    subprocess.run(cmd, cwd=det_root, env=env, check=True)
    run(
        [
            sys.executable,
            str(ROOT / "scripts" / "stage5_internimage_export_pkl.py"),
            "--ann",
            native("data/stage5_internimage/dfire/annotations/eval_all.json"),
            "--pkl",
            str(pkl),
            "--out",
            str(out / f"{arm}.csv"),
            "--meta",
            str(out / f"{arm}.pred_meta.json"),
        ]
    )


def write_meta(args, arms, epochs):
    meta = {
        "dataset": "dfire",
        "family": "internimage_t_maskrcnn",
        "family_label": "InternImage-T + Mask R-CNN",
        "paper_label": "InternImage-T based CNN detector",
        "seed": args.seed,
        "arms": arms,
        "epochs": epochs,
        "batch": args.batch,
        "run_root": str((ROOT / args.run_root).resolve()),
        "out_root": str((ROOT / args.out_root).resolve()),
        "model_note": "Official InternImage-T release uses Mask R-CNN; Cascade R-CNN is officially released for L/XL and is not used for the 3060 D-Fire third-model pilot.",
    }
    path = out_dir(args) / "run_meta.json"
    path.write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print(f"[meta] wrote {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, required=True)
    ap.add_argument("--arm", choices=list(ARM_GROUPS), default="all4")
    ap.add_argument("--mode", choices=["smoke", "train", "export", "eval", "all"], default="all")
    ap.add_argument("--epochs", type=int, default=300)
    ap.add_argument("--batch", type=int, default=2)
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--device", type=int, default=0)
    ap.add_argument("--run-root", default="runs/internimage/stage5_dfire")
    ap.add_argument("--out-root", default="formal_results/stage5_internimage")
    ap.add_argument("--overwrite", action="store_true")
    ap.add_argument("--mincheck", action="store_true")
    args = ap.parse_args()
    ensure_inputs()
    patch_mmdet_collect_env()
    arms = ARM_GROUPS[args.arm]
    epochs = 1 if args.mincheck else args.epochs
    if args.mode == "smoke":
        print(f"[smoke] family=internimage_t_maskrcnn seed={args.seed} arms={arms} epochs={epochs}")
        for arm in arms:
            cfg = config_path(args, arm, epochs)
            print(f"[smoke] {arm} ann={arm_ann(arm)} config={cfg}")
        return
    if args.mode in ("train", "all"):
        for arm in arms:
            train_arm(args, arm, epochs)
    if args.mode in ("export", "all"):
        for arm in arms:
            export_arm(args, arm, epochs)
    if args.mode in ("eval", "all"):
        run(
            [
                sys.executable,
                str(ROOT / "scripts" / "stage5_internimage_eval.py"),
                "--out-dir",
                str(out_dir(args)),
                "--arms",
                ",".join(arms),
                "--seed",
                str(args.seed),
            ]
        )
        write_meta(args, arms, epochs)


if __name__ == "__main__":
    main()
